equinor/fusion-react-components

packages/table/src/Table.tsx
packages/table/src/column/ColumnDefault.ts
packages/table/src/column/ColumnHeader.tsx
packages/table/src/types.ts

* add plugin for table
* add resizer to column header
CHANGE: table is now default flex table

feat: allow resize of columns

---

packages/datepicker/src/DatePicker.tsx
packages/datepicker/src/DatePickerHeader.tsx
packages/datepicker/src/DatePickerInput.tsx
packages/datepicker/src/types.ts
storybook/stories/datepicker/datepicker.stories.tsx

Fixed multiple bugs, see issue #23

fix: fixed multiple bugs and added label

---

packages/datepicker/src/DatePicker.tsx
packages/datepicker/src/DatePickerHeader.tsx
packages/datepicker/src/DatePickerInput.tsx

Fixed datepicker styling according to eds prototype.
Ref. issue #18 
Figma prototype:
https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=18146%3A5346

fix: fixed datepicker styling according to eds prototype

---

packages/datepicker/src/DatePicker.tsx
storybook/stories/datepicker/datepicker.stories.tsx

fix: fixed styling issues

---

packages/datepicker/package.json
packages/datepicker/src/DatePicker.tsx
packages/datepicker/src/react-datepicker.css.d.ts
packages/datepicker/src/react-datepicker.css.ts
packages/styles/src/index.ts

fix: fixed css styling issue

---

packages/checkbox/README.md
packages/switch/.eslintrc.js
packages/switch/CHANGELOG.md
packages/switch/README.md
packages/switch/package.json
packages/switch/src/Switch.tsx
packages/switch/src/declarations.d.ts
packages/switch/src/index.tsx
packages/switch/src/types.d.ts
packages/switch/tsconfig.json
storybook/package.json
storybook/stories/switch/switch.stories.mdx
storybook/tsconfig.json
tsconfig.json

feat: added switch react component

---

packages/radio/.eslintrc.js
packages/radio/CHANGELOG.md
packages/radio/README.md
packages/radio/package.json
packages/radio/src/Radio.tsx
packages/radio/src/declarations.d.ts
packages/radio/src/index.tsx
packages/radio/src/types.d.ts
packages/radio/tsconfig.json
storybook/package.json
storybook/stories/radio/radio.stories.mdx
storybook/tsconfig.json
tsconfig.json

feat: added radio component

---

packages/datepicker/package.json
packages/datepicker/src/DatePicker.tsx
packages/datepicker/src/DatePickerInput.tsx
packages/datepicker/src/style.tsx

fix: updated react-datepicker, fixed bugs and code refactoring

---

.github/workflows/pre-release.yml
lerna.json
packages/datepicker/package.json
packages/datepicker/src/DatePicker.tsx
packages/datepicker/src/index.tsx
packages/datepicker/src/style.tsx
packages/datepicker/src/types.ts
storybook/package.json
storybook/stories/datepicker/datepicker.stories.tsx

+ expose popper props
+ filter out custom props
+ override incomming props
+ expose classes for custom styling
+ strict export and default
+ replace them value with attributes
+ add story for popper offset
BREAKING CHANGES:
+ prop types might change type, now reflects native component
+ refactor of code might chage behavoir

feat: allow adjustment to popper

---

.github/workflows/pre-release.yml
packages/filter/package.json
packages/observable/package.json
packages/observable/src/hooks/useObservableEffect.ts
packages/observable/src/types.ts
storybook/package.json
storybook/src/stories/03-observables.stories.mdx

+ update docs for useObservableEffect

feat(observable): allow multiple effect

---

packages/table/src/Table.tsx
packages/table/src/TableProvider.tsx
packages/table/src/components/index.ts
packages/table/src/components/toolbar/ExportToExcelBtn.tsx
packages/table/src/components/toolbar/Toolbar.tsx
packages/table/src/components/toolbar/index.ts
packages/table/src/components/toolbar/types.ts
packages/table/src/layout/types.ts
packages/table/src/plugins/excel/actions.ts
packages/table/src/plugins/excel/index.ts
packages/table/src/plugins/excel/reducer.ts
packages/table/src/plugins/excel/types.ts
packages/table/src/plugins/excel/useExcel.ts
packages/table/src/plugins/excel/useInstance.ts
packages/table/src/plugins/menu/useInstance.ts
packages/table/src/types.ts
packages/table/src/useTable.ts
storybook/src/stories/table/BasicTable.stories.tsx
storybook/src/stories/table/ToolbarTable.stories.tsx

Had to make new PR because rebase merge issue
Now able to provide an excel export client and toolbar to the table component.

[Table] - Toolbar and export

---

packages/datepicker/src/DatePicker.tsx
packages/datepicker/src/components/DatePickerInput.tsx
packages/datepicker/src/style.ts
storybook/src/stories/datepicker/DatePicker.template.tsx

Move the label to the inside of the DatePicker input component.

feat: update styling for datepicker label

---

packages/list/package.json

Update fusion wc package to get overflow hidden on list element

chore(list): update wc package

---

packages/button/package.json

Update fusion wc-package to fix disabled for the button
fusion-web-components pr: https://github.com/equinor/fusion-web-components/pull/151

chore(button): update wc package

---

packages/filter/package.json
packages/filter/src/FilterProvider.tsx
storybook/package.json

- add memo to data and context
issues with perfomance when rerendering filter provider

fix(filter): optimize filter provider

---

packages/filter/src/components/filter/checkbox/CheckboxFilter.tsx
packages/filter/src/components/filter/checkbox/CheckboxFilterOptionAll.tsx
packages/filter/src/components/filter/checkbox/CheckboxFilterOptions.tsx
storybook/src/stories/filter/filter.checkbox.stories.tsx
storybook/src/stories/filter/generate-data.ts

feat(filter): add sortfn as a prop and capitalized  all label

---

packages/progress-indicator/README.md
packages/progress-indicator/src/circular.tsx
packages/progress-indicator/src/dots.tsx
packages/progress-indicator/src/index.ts
storybook/src/stories/progress-indicator/circular.examples.stories.tsx
storybook/src/stories/progress-indicator/circular.stories.mdx
storybook/src/stories/progress-indicator/dots.examples.stories.tsx
storybook/src/stories/progress-indicator/dots.stories.mdx
storybook/src/stories/progress-indicator/snapshots.stories.mdx
storybook/src/stories/progress-indicator/star.stories.mdx

https://statoil-proview.visualstudio.com/Fusion/_backlogs/backlog/Fusion%20Core/Epics/?workitem=26369
https://statoil-proview.visualstudio.com/Fusion/_backlogs/backlog/Fusion%20Core/Epics/?workitem=26370
Create react components based on the progress indicator web components called Circular and Dots.

Circular and Dots Progress Indicators

---

package-lock.json
package.json
packages/ag-grid-addons/package.json
packages/ag-grid-addons/src/agGridStyles/output/styles.ts
packages/ag-grid-addons/src/changeHandlerUtils/StatusComponent.tsx
packages/ag-grid-addons/src/changeHandlerUtils/constants.ts
packages/ag-grid-addons/src/changeHandlerUtils/dataManipulators.ts
packages/ag-grid-addons/src/changeHandlerUtils/defaultOptions.ts
packages/ag-grid-addons/src/changeHandlerUtils/index.ts
packages/ag-grid-addons/src/changeHandlerUtils/types.ts
packages/ag-grid-addons/src/index.ts
packages/ag-grid-addons/tsconfig.json

Util function for tracking input changes in ag grid
New functionality

feat:Ag grid - Change handler utils

---

packages/ag-grid-addons/src/changeHandlerUtils/index.ts

Added defaultOption export in index

fix: Ag grid - Added defaultOption export in index

---

packages/ag-grid-addons/src/agGridStyles/output/styles.ts
packages/ag-grid-addons/src/agGridStyles/styles.scss

Changed background color of selected row in ag grid addons package.

feat: added custom background color for ag grid selected row

---

packages/ag-grid-addons/package.json
packages/ag-grid-addons/src/agGridStyles/output/styles.ts
packages/ag-grid-addons/src/agGridStyles/styles.scss

There is issues with styling when switching to ag grid inside apps. For exabmle ag grid uses a line height which makes the personcard not display correctly. Also centering the component content in the cells are hard. 
Added a custom theme class based on ag theme alpine, and added centering and lineheight for cell class

Custom ag grid theme, with centered content in cells

---

packages/ag-grid-addons/src/agGridStyles/output/styles.ts
packages/ag-grid-addons/src/agGridStyles/styles.scss

fix: fixed wrong styling on previous pr for ag grid styling

---

packages/styles/package.json

fix(styles): peer deps

---

packages/ag-grid-addons/src/agGridStyles/output/styles.ts
packages/ag-grid-addons/src/agGridStyles/styles.scss

feat: added centering on exandable ag grid cells

---

package-lock.json
packages/ag-grid-styles/gulpfile.js
packages/ag-grid-styles/package.json
packages/ag-grid-styles/src/agGridStyles/styles.css.ts
packages/ag-grid-styles/src/agGridStyles/styles.scss
packages/ag-grid-utils/package.json
packages/ag-grid-utils/src/changeHandlerUtils/StatusComponent.tsx
packages/ag-grid-utils/src/changeHandlerUtils/defaultOptions.ts

Changes package ``ag-grid-community`` to ``@ag-grid-community/core``
The packages ``ag-grid-utils`` and ``ag-grid-styles`` needed the peer dependencie ``@ag-grid-community/core``

fix/ag grid community/package

---

packages/ag-grid-styles/gulpfile.js
packages/ag-grid-styles/package.json
packages/ag-grid-styles/src/agGridStyles/styles.css.ts
packages/ag-grid-styles/src/agGridStyles/styles.scss
packages/ag-grid-styles/src/agGridStyles/useAgGridStyles.ts
packages/ag-grid-styles/src/index.ts

Close #416 
Fixes issue concerning font unicode in css content attribute.
Adds ``@ag-grid-community`` as devDependencie in addition to peerDependencie.
Exports ``useStyles`` hook from package.
See above section

Fix/ag grid styles/issue/416

---

packages/ag-grid-styles/src/agGridStyles/styles.css.ts
packages/ag-grid-styles/src/agGridStyles/styles.scss
packages/ag-grid-styles/src/agGridStyles/useAgGridStyles.ts

Close #419 
Add EDS variables to ag-grid fusion theme
Overwrite the default ag-grid variables with eds values. No need to add scss values for it.

fix(ag-grid-styles): added variables from EDS. Resolves #419

---

packages/ag-grid-utils/src/changeHandlerUtils/StatusComponent.tsx
packages/ag-grid-utils/src/changeHandlerUtils/defaultOptions.ts

Small Ad hoc fix needed for using the status component with grouped columns in AGgrid

Bugfix - AG grid status component

---

packages/filter/src/components/panel/FilterPanel.tsx
packages/filter/src/components/panel/FilterPanelBar.tsx

…o use in seachbar
https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/27596/
Search in filter panel does not return expected results as it only can use default search function which uses all props on dataset. 
This change adds a searchFn parameter to filterpanel so one can specify custom search function for search bar instead of default one.

feat: filter, filterpanel search bar function prop

---

packages/person/package.json

updating Person dependency with latest  version from fusion-web-components.
Updating @equinor/fusion-wc-person from v0.3.3 to 0.3.6.

fix(person): import latest person version from web components

---

packages/context-selector/src/ContextSelector.tsx
packages/searchable-dropdown/package.json
storybook/src/stories/context-selector/contextResolver.tsx

Renaming contextselector types and updating searchabledropdown from web component to 0.3.1

fix: updating webcomponent renaming contextsel type

---

packages/searchable-dropdown/package.json

Updates dependency for ``fwc-searchable-dropdown`` to 0.3.2.

chore(searchable-dropdown): updating webcomponent to 0.3.2

---

packages/ag-grid-styles/package.json

fix: :bug: fix missing deps in ag-grid-styles

---

packages/context-selector/src/ContextSelector.tsx

Exporting types as ContextSelector types and not SearchableDropdown.

fix(contextselector): exporting types properly

---

packages/searchable-dropdown/package.json

Bumping searchabledropdown dependency from fwc to 2.0.1.

fix(searchable-dropown): bumping fwc-searchable-dropdown

---

packages/context-selector/src/ContextSelector.tsx
packages/searchable-dropdown/package.json
packages/searchable-dropdown/src/Dropdown.tsx

Setting SearchableDropdown type on react event ``onSelect`` by extending the fwc ``select`` event type.
Exporting alias type for ``ContextSelector``.
Bumping ``fusion-wc-searchable-dropdown`` to latest version.

Fix/context dropdown/types

---

packages/button/package.json
packages/button/src/index.tsx
storybook/src/stories/list/examples.stories.tsx
tsconfig.json

Fixes wrong import of tag from fusion-fw-button, its now named buttonTag.

fix(button): fixes import of tag to buttonTag from fusion-wc-button

---

packages/ag-grid-utils/src/changeHandlerUtils/StatusComponent.tsx

The status column should have more statuses, allowing for other states than saved / unsaved to be shown.
Status column now only show two states, changed or new, and saved. Using the aggrid status patched, the column now show a "middle" status between these two. Using a orange circkled check.

feat: added extra status column in ag grid statuc column

---

storybook/src/stories/datepicker/DatePicker.template.tsx
storybook/src/stories/datepicker/component.stories.mdx

Added usable base datepicker properties to aruments list and documented custom properties.
Usable base date-picker properties to arguments list and documented custom properties.
Close #29 
[Issue #29 [Datepicker] missing documentation](https://github.com/equinor/fusion-react-components/issues/29)
Added documentation for date-picker

docs: :memo: datepicker documentation

---

packages/person/src/index.tsx

Added additional export types from fusion-wc-person
Export types like PersonDetails are needed when creating default person resolver, so we exported them web component to our newly created react component

fix: :bug: additional type export

---

packages/context-selector/src/ContextSearch.styles.ts
packages/context-selector/src/ContextSearch.tsx
packages/context-selector/src/types.ts
packages/searchable-dropdown/src/Dropdown.tsx
packages/searchable-dropdown/src/DropdownProvider.tsx
packages/searchable-dropdown/src/SearchableDropdown.tsx
packages/searchable-dropdown/src/useDropdownProviderRef.ts
storybook/src/stories/context-selector/component.helpers.tsx
storybook/src/stories/context-selector/examples.stories.tsx
storybook/src/stories/searchable-dropdown/examples.stories.tsx

Remembers context after selecting.
Closes  #912 in fusion-cli.
See commit log.

Fix/context search/selected

---

packages/button/package.json
packages/button/src/index.tsx
packages/checkbox/src/index.tsx
packages/context-selector/src/ContextSearch.tsx
packages/person/src/index.tsx
packages/radio/src/index.tsx
packages/searchable-dropdown/package.json
packages/switch/src/index.tsx
packages/table/src/layout/types.ts
packages/table/src/plugins/excel/types.ts
packages/table/src/plugins/menu/types.ts
storybook/src/stories/menu/examples.stories.tsx
storybook/src/stories/person/avatar.stories.tsx

Show property ``initialItem`` as selected in UI.
updating to newest SearchableDropdown from fwc.

feat(ContextSearch): show initialItem as selected

---

packages/context-selector/src/ContextProvider.tsx
packages/context-selector/src/ContextSelector.tsx
packages/context-selector/src/types.ts
packages/searchable-dropdown/package.json
storybook/src/stories/context-selector/component.helpers.tsx
storybook/src/stories/searchable-dropdown/component.helpers.tsx
tsconfig.json

chore(dsearchable-dd): bumping fwc-searchable-dropdown to 2.5.1

---

packages/context-selector/src/ContextSearch.tsx

delegate focus to text-input when on component.

fix(ContextSearch): setting focus on input when clicking wrapper

---

packages/person/package.json
packages/person/src/PersonCard.tsx
packages/person/src/PersonListItem.tsx
packages/person/src/index.tsx
storybook/src/stories/person/card.stories.mdx
storybook/src/stories/person/card.stories.tsx
storybook/src/stories/person/list-item.stories.mdx
storybook/src/stories/person/list-item.stories.tsx

[Design and functionality rework of PersonCard component + PersonListItem](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/36194)
Created new react component called Person List Item that shows Person Card when you click on it

Feat/react components/person list item

---

package-lock.json
packages/datepicker/package.json
packages/datepicker/src/style.ts
storybook/package.json

fix(datepicker): updated styling for react datepicker month calendar

---

package-lock.json
packages/styles/package.json
storybook/package.json

chore: update fwc-style

---

packages/chip/package.json

chore(chip): update dependencies

---

packages/ag-grid-styles/src/agGridStyles/styles.scss

[[React components] AGgridSyles](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/41508)
In Fusion react styles component for AGgrid, remove unnecessary CSS
Fix bug with `display: flex` not allowing columns when they resize to use `text-overflow: ellipsis`

fix(ag-grid-styles): ag-cell css remove

---

packages/button/package.json
packages/button/src/icon-button-toggle/index.tsx
packages/button/src/index.tsx
storybook/src/stories/button/icon-button-toggle/examples.stories.tsx
storybook/src/stories/button/icon-button/examples.stories.tsx

Update to changed web component and adjust component

chore(button): update icon button

---

packages/markdown/package.json
packages/markdown/src/MarkdownEditor.tsx
storybook/src/stories/markdown/markdown-editor/component.stories.mdx
storybook/src/stories/markdown/markdown-editor/examples.stories.tsx

on copy/paste in markdown editor trigger onInput event
[[Markdown] Copy/paste not triggering onInput](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/42058)
close #652
Create new custom event and trigger it onInput in react components
- [x Assign relevant reviewers in Github and Chromatic

fix(markdown-editor): onInput event

---

packages/stepper/CHANGELOG.md
packages/stepper/README.md
packages/stepper/package.json
packages/stepper/src/Step.tsx
packages/stepper/src/StepContent.tsx
packages/stepper/src/StepPane.tsx
packages/stepper/src/Stepper.tsx
packages/stepper/src/index.tsx
packages/stepper/src/style.ts
packages/stepper/tsconfig.json
storybook/package.json
storybook/src/stories/stepper/component.stories.mdx
storybook/src/stories/stepper/component.stories.tsx
storybook/tsconfig.json
tsconfig.json

New stepper component, created from stepper in react components
[As a app developer, I want to have stepper as a react component so that app teams can reuse it](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/41948)
[Create a stepper componen](https://github.com/equinor/fusion-react-components/issues/816)
close #816
Create a stepper in react components

feat(stepper): stepper component

---

packages/person/package.json

fix(person) - force release

---

packages/person/src/PersonListItem.tsx
packages/styles/src/ThemeProvider.tsx
storybook/package.json

fix(person): popover import

---

packages/person/src/PersonListItem.tsx

fix(popover): popover import

---

packages/ag-grid-addons/src/agGridStyles/output/styles.ts
packages/ag-grid-styles/src/agGridStyles/styles.jss.json

[[ContractPersonnel] Table icons aren't loading](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/43212/)
Added `!important` to every font family for icons and radio buttons and inputs, since portal overrides font family of AGgrid

fix(agGridStyles): all buttons font-family fix

---

packages/ag-grid-addons/src/agGridStyles/output/styles.ts
packages/ag-grid-styles/src/agGridStyles/styles.jss.json
packages/ag-grid-styles/src/agGridStyles/styles.scss

[[ContractPersonnel] Table icons aren't loading](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/43212/)

fix(agGrid-styles): added new custom class

---

packages/ag-grid-styles/src/agGridStyles/styles.scss

added font family for all icon classes

fix(agGrid-styles): added font family for all icon classes

---

packages/stepper/package.json
packages/stepper/src/Step.tsx
packages/stepper/src/StepPane.tsx
packages/stepper/src/Stepper.tsx
packages/stepper/src/style.ts
packages/stepper/src/utils.ts
storybook/src/stories/stepper/component.stories.mdx
storybook/src/stories/stepper/component.stories.tsx

[As a developer, I want to be able to complete steps and to see completed steps in stepper component](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/43179)
- Swap buttons with EDS
- Make steps **done** (works with stepper that doesn't force order)
- Availability to show all steps and their properties (on change)
```tsx
return {
key: child.props.stepKey,
position: i + 1,
disabled: child.props.disabled ?? false,
done: child.props.done ?? false,
}
```
- Fix forceOrder stepper

Feat/react components/stepper

---

storybook/src/components/StoryExample.tsx
storybook/src/stories/person/PersonResolve.tsx
storybook/src/stories/person/avatar-component.stories.mdx
storybook/src/stories/person/card-component.stories.mdx
storybook/src/stories/person/list-item-component.stories.mdx
storybook/src/stories/person/provider-component.stories.mdx

Fix/person component/provider page

---

packages/ag-grid-styles/src/agGridStyles/styles.jss.json
packages/person/package.json
packages/person/src/PersonAvatar.tsx
packages/person/src/PersonCard.tsx
packages/person/src/PersonListItem.tsx
packages/person/src/index.tsx

fix(agGrid-style): builded style

---

storybook/src/components/StoryExample.tsx

fix(storybook): show story url

---

storybook/src/stories/person/provider-component.stories.mdx

feat(storybook): person details type

---

packages/filter/src/FilterProvider.tsx
packages/filter/src/components/filter/checkbox/CheckboxFilterProvider.tsx
packages/filter/src/components/panel/FilterPanel.tsx
packages/filter/src/components/panel/FilterPanelProvider.tsx
packages/filter/src/context.ts
packages/filter/src/options/FilterOptionProvider.tsx
packages/filter/src/options/context.ts
packages/hanging-garden/src/components/PopoverContainer/index.tsx
packages/hanging-garden/src/renderHooks/useHangingGardenContext.tsx

fix(react-components): type fixes

---

packages/markdown/src/MarkdownViewer.tsx
packages/markdown/src/index.tsx
storybook/src/stories/markdown/markdown-viewer/component.stories.mdx
storybook/src/stories/markdown/markdown-viewer/examples.stories.tsx

Closes #716
This will add a markdown viewer react component.
Adds a new component for viewing markdown as html.

feat(markdown): add markdown-viewer

---

.changeset/eight-queens-behave.md
packages/avatar/README.md

feat(avatar): deprecate avatar

---

.changeset/dry-cheetahs-end.md
packages/badge/README.md

feat(badge): deprecate

---

.changeset/tame-lobsters-grab.md
.github/workflows/lint.yml
packages/searchable-dropdown/package.json
pnpm-lock.yaml

chore(searchable-dropdown): update

---

.changeset/dry-ducks-knock.md
packages/chip/README.md
packages/filter/package.json
packages/filter/src/components/misc/SelectionChips.tsx
pnpm-lock.yaml
storybook/src/stories/filter/filter.checkbox.stories.tsx

feat(chip): deprecate chip

---

.changeset/ninety-bananas-camp.md
packages/side-sheet/package.json
packages/side-sheet/src/components/SideSheetBase.tsx
pnpm-lock.yaml

feat: update side sheet with latests EDS

---

.changeset/purple-humans-cheer.md
packages/ag-grid-styles/package.json
pnpm-lock.yaml

Updating ag-grid dependency to 30.2 in ag-grid-styles.
Closes #982

Chore/ag grid styles/ag grid version

---

.changeset/eight-rats-play.md
packages/side-sheet/src/components/Indicator.tsx

Added missing borde radius to side sheet indicator
#754

chore: added missing border radius 2px

---

.changeset/breezy-ways-doubt.md
packages/side-sheet/src/components/SideSheetBase.tsx

The side-sheet should be displayed beneath the portal header, ensuring that no content is obscured or hidden.

fix(sidesheet): sidesheet header is hidden behind fusion top bar

---

.changeset/loud-peas-type.md
packages/context-selector/src/ContextSearch.tsx

unmount the context-selector's dropdown when navigating to context with url

Chore/context selector/dropdown/hide dom inactive

---

.changeset/flat-dolls-grow.md
packages/person/src/PersonAvatar.tsx
storybook/src/stories/person/avatar-component.stories.mdx

fix(person): expose `trigger` attribute from avatar

---

.changeset/tough-pants-reply.md
packages/filter/src/components/misc/ClearFilterButton.tsx
packages/filter/src/components/panel/FilterPanelBar.tsx

feat(filter): remove fusion button

---

.changeset/nasty-ladybugs-join.md
packages/filter/src/components/panel/FilterPanelBar.tsx
packages/person/package.json
pnpm-lock.yaml

Updating Person components dependency: [@equinor/fusion-wc-person to 2.3.0](https://github.com/equinor/fusion-web-components/blob/main/packages/person/CHANGELOG.md#230)

chore(person): updating wc dependency

---

.changeset/calm-bulldogs-approve.md
.changeset/serious-wombats-complain.md
packages/side-sheet/src/components/Content.tsx
packages/side-sheet/src/components/SideSheet.tsx
packages/side-sheet/src/components/SideSheetBase.tsx
packages/stepper/src/style.ts

fix(stepper): stepper height

---

.changeset/lemon-donuts-suffer.md
packages/context-selector/package.json
packages/searchable-dropdown/package.json
pnpm-lock.yaml
storybook/src/stories/context-selector/component.stories.mdx

[AB#44766](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/44766)

build(deps): bump @equinor/fusion-wc-searchable-dropdown to 3.7.0 + update storybook

---

.changeset/chatty-seas-behave.md
packages/ag-grid-styles/src/agGridStyles/styles.jss.json
packages/person/package.json
pnpm-lock.yaml

Fixing deselecting person in the PersonSelectEvent details, show now as null when none is selected.
Ref: [AB#48075](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/48075)

chore(person-select): bump fusion-wc-person to resolve onSelect

---

.changeset/honest-rings-lay.md
packages/ag-grid-styles/src/agGridStyles/styles.jss.json
packages/list/package.json
packages/list/src/components/CheckListItem.tsx
packages/list/src/components/ListItem.tsx
packages/list/src/components/RadioListItem.tsx
pnpm-lock.yaml

updates web component fwc-list to resolve issue with chromatic build.

fix(list): fixes error when building cromatic on list component

---

.changeset/rare-news-wonder.md
packages/person/package.json
pnpm-lock.yaml

build(deps): bump @equinor/fusion-wc-person from 2.3.2 to 2.4.0

---

.changeset/famous-cougars-rule.md
packages/person/package.json
packages/person/src/PersonSelect.tsx
pnpm-lock.yaml

Ref equinor/fusion-web-components#1375
Ref [AB#48493](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/48493)

chore(deps): update @equinor/fusion-wc-person to 2.5.1

---

.changeset/thirty-turtles-train.md
storybook/src/stories/person/resolve-mock/person-resolve-mock.tsx
storybook/src/stories/person/select-component.stories.mdx
storybook/src/stories/person/select-example.stories.tsx

Ref [AB#47637](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/47637)
Adds storybook entry for selectedPerson. Remove unused attributes from docs.

docs(storybook): story for PersonSelect selectedPerson attribute

---

.changeset/calm-otters-search.md
packages/person/package.json
pnpm-lock.yaml

Updates the `fusion-wc-person` dependency to implement latest fixes.

chore(person): updating fosion-wc-person

---

.changeset/weak-zoos-visit.md
storybook/src/stories_v7/person/person-provider.ts

Storybook support for searching by upn and azureId in personProvider

---

.changeset/chilled-frogs-press.md
packages/context-selector/package.json
pnpm-lock.yaml

Update of searchable dropdown web component in context selector

chore(context-selector): wc searchable update

---

.changeset/chilled-yaks-travel.md
packages/person/package.json
pnpm-lock.yaml

Update deps for person components

chore(person): deps

---

.changeset/early-colts-rescue.md
packages/list/package.json
pnpm-lock.yaml

Removes unused, and deprecated, dependency from list component.

chore(list): removes @lit-labs/react from list component

---

.changeset/rude-icons-share.md
packages/ag-grid-styles/package.json
packages/ag-grid-styles/src/agGridStyles/styles.jss.json
packages/ag-grid-utils/package.json
pnpm-lock.yaml
storybook/package.json

Updates aggrid packages to have same version as framework.

fix(ag-grid): updating aggrid deps to align with fusion-framework

---

.changeset/many-pillows-divide.md
storybook/src/stories/searchable-dropdown/component.helpers.tsx

Using faker data in searchabledropdown stories.
Closes #1515

chore(searchable-dropdown): faker data on results in storybook

---

.changeset/late-ways-punch.md
package.json
packages/ag-grid-styles/README.md
packages/ag-grid-styles/gulpfile.js
packages/ag-grid-styles/package.json
packages/ag-grid-styles/src/agGridStyles/styles.scss
packages/ag-grid-styles/src/agGridStyles/useAgGridStyles.ts
pnpm-lock.yaml

- Cleanup AgGrid style with adding `alpine-active-color` to main style theme
- In order to fix not beeing able to click on checkbox in AgGrid, removed `indicateEditMode` from **useStyle**
[AB#52972](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/52972)

fix(ag-style): style cleanup and checkbox fix

---

.github/dependabot.yml

chore(dependabot): group all storybook updates

---

.changeset/late-fishes-wash.md
packages/side-sheet/src/components/SideSheet.tsx

[AB#54660](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/54660)
Add tooltip to side sheet buttons

fix(side-sheet): button tooltips

---

.changeset/serious-queens-move.md
packages/person/package.json
pnpm-lock.yaml

chore(person): update dep @equinor/fusion-wc-person to 2.6.9

---

.changeset/witty-insects-trade.md
packages/ag-grid-person-cell/src/agPersonCell.tsx
packages/person/package.json
pnpm-lock.yaml
storybook/src/stories/ag-grid-person-cell/ag-grid-person-cell.stories.tsx

AgGrid person cell update of:
- Storybook
- Dependencies

Chore/ag person cell/update

---

.github/dependabot.yml

Adds dependabot group for ``@equinor/fusion-wc-*`` packages

chore(dependabot): adding group for fusion-wc-*

---

.changeset/fair-squids-cross.md
.changeset/shiny-avocados-serve.md
package-lock.json
package.json
packages/person/src/PersonAvatar.tsx
packages/person/src/PersonCard.tsx
packages/person/src/PersonCell.tsx
packages/person/src/PersonListItem.tsx
packages/person/src/PersonProvider.tsx
packages/person/src/PersonSelect.tsx
packages/utils/src/create-element.ts
packages/utils/src/element-attributes.ts
packages/utils/src/hooks/useElementEvents.ts
packages/utils/src/hooks/useElementFunctions.ts
packages/utils/src/hooks/useElementProps.ts
packages/utils/src/hooks/useForwardRef.ts

improves interopt between react and web-components

Feat(utils): improve web-component interopt

---

.changeset/witty-insects-trade.md
packages/person/package.json
pnpm-lock.yaml
storybook/src/stories/ag-grid-person-cell/ag-grid-person-cell.stories.tsx

Chore/react components/person component update

---

.changeset/flat-candles-drum.md
packages/context-selector/package.json
packages/searchable-dropdown/package.json
pnpm-lock.yaml
storybook/src/stories/searchable-dropdown/searchable-dropdown.mdx
storybook/src/stories/searchable-dropdown/searchable-dropdown.stories.tsx

- `@equinor/fusion-react-searchable-dropdown`: major
- `@equinor/fusion-react-context-selector`: major
Implementing fixes from searchable-dropdown web component release [44aa0a8](https://github.com/equinor/fusion-web-components/commit/44aa0a8b744e873e19ee6fa9e92da0bd8c3031d8)
This fixes multiple selections in searchable-dropdown and adding support for using html as meta icons in the result set.
also fixes using attribute `selectedId` as preselected id, works best with initialItems from resolver.
Updating to major version to make sure nothing in production brakes.

Feat/fwc searchable dropdown/major update

---

.changeset/few-cows-search.md
packages/ag-grid-person-cell/package.json
packages/ag-grid-person-cell/src/agPersonCell.tsx
packages/ag-grid-person-cell/src/personTooltip.tsx
packages/ag-grid-person-cell/tsconfig.json
pnpm-lock.yaml
storybook/package.json
storybook/src/stories/ag-grid-person-cell/ag-grid-person-cell.stories.tsx

AgGrid version 33, possible braking changes
- Updated types and dependencies to newest AgGrid version
- Now using and depended on _@equinor/fusion-framework-module-ag-grid_

chore(ag-person-cell): ag grid 33 major update

---

.changeset/shy-owls-hammer.md
packages/ag-grid-person-cell/tsconfig.json
packages/ag-grid-utils/package.json
packages/errorboundary/package.json
pnpm-lock.yaml
storybook/src/stories/ag-grid-person-cell/ag-grid-person-cell.stories.tsx

fix(ag-grid): update eds deps

---

.github/workflows/actions/node-setup/action.yml
package.json

build: update Node.js version to 22 and bump pnpm to 10.5.1

---

.changeset/hip-views-fry.md
packages/ag-grid-person-cell/package.json
packages/ag-grid-person-cell/src/agPersonCell.tsx
pnpm-lock.yaml
storybook/src/stories/ag-grid-person-cell/ag-grid-person-cell.stories.tsx

Update dependencies for ag-grid and refactor imports to use the new package structure. This change enhances compatibility and maintains functionality.

Update ag-grid dependencies and refactor imports

---

.changeset/social-ends-thank.md
.changeset/twenty-onions-poke.md
packages/context-selector/package.json
packages/date/package.json
packages/filter/package.json
packages/list/package.json
packages/markdown/package.json
packages/person/package.json
packages/ripple/package.json
packages/searchable-dropdown/package.json
packages/skeleton/package.json
packages/styles/package.json
packages/textarea/package.json
pnpm-lock.yaml
storybook/package.json

Upgrade ag-grid and various fusion-wc dependencies to their latest versions to ensure compatibility and access to new features.

Update dependencies for ag-grid and fusion-wc components

---

.changeset/stale-horses-share.md
packages/ag-grid-utils/package.json
packages/ag-grid-utils/src/changeHandlerUtils/StatusComponent.tsx
packages/ag-grid-utils/src/changeHandlerUtils/defaultOptions.ts
packages/ag-grid-utils/tsconfig.json
pnpm-lock.yaml
storybook/src/stories/ag-grid/ag-grid-utils.stories.tsx

BREAKING: AG-Grid major update

feat!(ag-grid-utils): upgrade ag-grid to 33

---

.changeset/bright-planets-serve.md
packages/context-selector/package.json
packages/searchable-dropdown/package.json
pnpm-lock.yaml

fix(searchable-dropdown): update deps wc searchable dropdown to 4.0.3

---

.changeset/slow-parents-occur.md
packages/side-sheet/src/components/SideSheet.tsx

Add custom variables for side sheet header height and padding

fix(side-sheet): custom height vars

---

.changeset/healthy-otters-cover.md
packages/person/package.json
pnpm-lock.yaml

fix(person): update deps wc person to 3.1.7

---

.changeset/poor-bars-take.md
packages/ag-grid-utils/package.json
packages/errorboundary/package.json
packages/filter/package.json
packages/side-sheet/package.json
packages/stepper/package.json
pnpm-lock.yaml
storybook/package.json
storybook/tsconfig.json

fix(storybook): fixes build issues

---

.changeset/rare-berries-drum.md
packages/person/README.md
packages/person/src/PersonProvider.tsx
storybook/src/stories/person/provider/provider.mdx
storybook/src/stories/person/provider/provider.stories.tsx

Example story for PersonProvider

feat(storybook): story for PersonProvider

---

.changeset/loose-pots-report.md
packages/side-sheet/src/components/SideSheet.tsx
storybook/src/stories/sidesheet/side-sheet.stories.tsx

Also update storybook examples
Ref equinor/fusion#644

fix(side-sheet): position action buttons when no title is used

---

.changeset/tame-roses-die.md
.changeset/tame-roses-fly.md
packages/person/package.json
pnpm-lock.yaml
storybook/src/stories/ag-grid/ag-grid-person-cell/ag-grid-person-cell.mdx
storybook/src/stories/ag-grid/ag-grid-person-cell/ag-grid-person-cell.stories.tsx
storybook/src/stories/ag-grid/ag-grid-utils/ag-grid-utils.stories.tsx

Update wc-person in react-person to fix issue with long titles in PersonCard.
Reported by @Apalhagen
Closes https://github.com/equinor/fusion/issues/680

Fix/person cell/ag grid row click card
